#!/usr/bin/perl -pw

use strict;
use Convert::Color::HUSL;

sub husl($) {
	my @husl = ($ENV{HUE}, 100, @_);
	my @rgb = map { 255 * $_ } Convert::Color::HUSL->new(@husl)->rgb;
	sprintf "#%02x%02x%02x", @rgb;
}

my %colors = (
	foreground => husl(14),
	accent     => husl(37),
	focus      => husl(43),
	main       => husl(49),
	background => husl(96),
);

s/\$(\w+)/$colors{$1}/g;
